affirmations = [
    "I am worthy of love, just as I am. Every day, I grow kinder to myself.",
    "My heart deserves peace, and I welcome it gently into my life.",
    "I am not defined by my struggles — I am defined by my strength.",
    "I allow myself to rest, to breathe, and to heal.",
    "My value is not measured by my mistakes but by my resilience.",
    "I am learning to love myself more deeply with each passing day.",
    "My presence matters, my voice matters, I matter.",
    "I give myself permission to feel joy, even in small moments.",
    "I am patient with myself and honor my journey.",
    "I let go of harsh self-judgment and replace it with compassion.",
    "I am a work of art, ever-growing, ever-healing.",
    "I forgive myself for the times I forgot my own worth.",
    "I choose to nurture myself like a dear friend.",
    "I am worthy of the dreams I hold in my heart.",
    "I trust my path, even when I cannot see the whole way.",
    "My heart is learning softness, even after hurt.",
    "I am whole, even when I feel broken.",
    "I release the weight of comparison my journey is my own.",
    "I honor the small steps I take toward healing.",
    "I deserve to be treated with kindness, by myself and others.",
    "My worth does not depend on my productivity.",
    "I allow myself to bloom in my own timing.",
    "I carry beauty within me, even when I forget to notice it.",
    "I am proud of how far I've come, even if no one else sees it.",
    "I belong here, in this moment, exactly as I am.",
    "Each day, healing flows through me like gentle sunlight.",
    "My pain is valid, but it does not define my future.",
    "Hope lives quietly inside me, and I choose to nurture it.",
    "I release what I cannot control and open myself to peace.",
    "My heart is mending in its own rhythm, and that is enough.",
    "I welcome the possibility of brighter days ahead.",
    "Healing is not linear, and I honor every step of the process.",
    "Even the smallest progress is still progress.",
    "I trust that every ending makes space for new beginnings.",
    "I breathe in calm and exhale what no longer serves me.",
    "I choose to see this moment as a chance to start again.",
    "My spirit is stronger than my struggles.",
    "I allow myself to feel, knowing that emotions are part of healing.",
    "With each sunrise, I receive another chance to grow.",
    "My future is filled with possibilities that I cannot yet imagine.",
    "The pain I feel today will one day be a story of survival.",
    "I carry seeds of hope, and they are blooming within me.",
    "I am open to receiving love, light, and healing energy.",
    "My past does not chain me; I am free to create anew.",
    "I embrace uncertainty with faith that things will work out.",
    "Healing is my birthright, and I claim it with courage.",
    "Even in silence, I am supported by life's gentle forces.",
    "I am learning to live with both my scars and my strength.",
    "Hope is a quiet flame in me, steady and unshakable.",
    "I believe in the possibility of joy returning to me.",
    "I am stronger than I realize, braver than I believe.",
    "Every challenge I face is shaping me into who I'm meant to be.",
    "My resilience grows each time I choose to keep going.",
    "I have survived difficult days before, and I can again.",
    "My strength is not in never falling, but in always rising.",
    "I carry a quiet power within me that cannot be broken.",
    "I trust my ability to handle whatever comes my way.",
    "Even in storms, I remain grounded like a rooted tree.",
    "I am proud of how I've endured and kept moving forward.",
    "Hardships build my wisdom and my courage.",
    "My scars are proof of my strength, not signs of weakness.",
    "I face difficulties with calm determination.",
    "I am a survivor, not a victim.",
    "Every step forward, no matter how small, is a triumph.",
    "I adapt, I rise, I grow nothing can hold me down.",
    "I trust the strength in my mind, body, and soul.",
    "My inner fire keeps me moving through dark times.",
    "I stand tall, even when the world feels heavy.",
    "I turn obstacles into opportunities for growth.",
    "My resilience is limitless; my courage is unshakable.",
    "I am capable of handling whatever this day brings.",
    "I recover quickly, because strength flows through me.",
    "No matter how hard it gets, I never give up on myself.",
    "My persistence turns challenges into victories.",
    "I am unbreakable in spirit, unstoppable in growth.",
    "I inhale peace, I exhale tension.",
    "My mind is a calm lake, steady and serene.",
    "I choose peace over worry, calm over chaos.",
    "In this moment, I am safe, I am at ease.",
    "My breath anchors me to stillness.",
    "I release all tension from my body and welcome softness.",
    "My heart is calm, my thoughts are gentle.",
    "I allow myself to slow down and rest.",
    "Peace flows through me with every deep breath.",
    "I do not chase calm I create it within.",
    "My mind is clear, my body is relaxed, my soul is at ease.",
    "I am not my stress; I am the calm beyond it.",
    "Stillness is my strength and my refuge.",
    "With every breath, I release what I cannot control.",
    "My inner world is filled with light and tranquility.",
    "I let go of all that disturbs my peace.",
    "I choose to respond with calm, not react with fear.",
    "The present moment is my safe space.",
    "I create a sanctuary of peace within myself.",
    "My calm presence influences everything around me.",
    "I release restlessness and embrace stillness.",
    "I am grounded, steady, and centered.",
    "Each pause I take fills me with peace.",
    "Quiet moments are powerful and healing for me.",
    "I am at home in my own calm energy.",
    "I am grateful for the gift of another day.",
    "My heart notices the small joys that surround me.",
    "Gratitude fills me and multiplies my blessings.",
    "I focus on what's going right instead of what's going wrong.",
    "Each challenge has hidden lessons to be thankful for.",
    "My life is rich with moments of beauty and kindness.",
    "I welcome today with an open and grateful heart.",
    "I choose to smile, even for the simplest reasons.",
    "I radiate positivity and attract good energy.",
    "Gratitude shifts my perspective and lifts my spirit.",
    "I find something to appreciate in every situation.",
    "My heart overflows with thanks for the love I receive.",
    "Even ordinary days carry extraordinary blessings.",
    "I focus on abundance, not lack.",
    "My gratitude creates room for more joy to enter my life.",
    "I am thankful for my growth, both big and small.",
    "Positivity is my natural state, and I return to it with ease.",
    "I choose to see the bright side of every moment.",
    "Gratitude softens my heart and heals my spirit.",
    "I celebrate even the tiniest wins in my life.",
    "I am thankful for the people who bring light into my world.",
    "Optimism is my compass, guiding me forward.",
    "I let gratitude replace worry in my heart.",
    "Each breath I take is a reason to be thankful.",
    "My joy multiplies when I focus on gratitude.",
    "I walk forward with courage, even when I feel fear.",
    "My confidence grows stronger with each step I take.",
    "I trust myself to handle whatever comes my way.",
    "I am proud of the person I am becoming.",
    "I am fearless in the pursuit of what matters to me.",
    "My voice deserves to be heard, and I speak with clarity.",
    "Courage flows through me, steady and unshakable.",
    "I believe in myself and my unique abilities.",
    "Confidence shines from me effortlessly.",
    "I stand tall in my truth and strength.",
    "My bravery is greater than my doubts.",
    "I let go of hesitation and embrace action.",
    "Confidence is my natural state of being.",
    "Every small risk I take strengthens my courage.",
    "I trust the wisdom of my heart and mind.",
    "I choose faith over fear, action over worry.",
    "I radiate self-assurance and inner power.",
    "I am not afraid to shine brightly.",
    "My courage inspires others around me.",
    "I believe in my ability to create change.",
    "I release self-doubt and welcome confidence.",
    "I am bold, capable, and worthy of success.",
    "Every day, my courage becomes more natural.",
    "I face challenges head-on with strength and grace.",
    "I am unstoppable when I trust myself fully.",
    "I am worthy of deep, genuine love.",
    "My heart is open to giving and receiving love.",
    "I attract relationships that nurture and uplift me.",
    "I deserve connections that bring me peace and joy.",
    "I release past hurts and make space for healthy love.",
    "My relationships are filled with kindness and respect.",
    "I allow love to flow freely in my life.",
    "I choose to surround myself with people who care for me.",
    "My love for myself makes my relationships stronger.",
    "I forgive and let go, creating space for harmony.",
    "I am grateful for the love that already exists in my life.",
    "My friendships are rooted in trust and compassion.",
    "I attract people who honor my boundaries.",
    "I give love without fear and receive love without doubt.",
    "My heart glows with warmth for those I care about.",
    "I deserve relationships that are balanced and fulfilling.",
    "I am loved more than I sometimes realize.",
    "I choose to show love in small and meaningful ways.",
    "I attract relationships that align with my true self.",
    "Love finds me in unexpected and beautiful ways.",
    "I release toxic connections and welcome healthy ones.",
    "My presence brings comfort and joy to others.",
    "I trust in the timing of love in my life.",
    "I am worthy of a love that feels safe and real.",
    "I nurture the connections that make my soul feel alive.",
    "Every day is a fresh start filled with new possibilities.",
    "I embrace change as a path to growth.",
    "I welcome new beginnings with courage and hope.",
    "My past does not limit the person I am becoming.",
    "I grow wiser and stronger with each experience.",
    "Each step I take leads me closer to my true self.",
    "I see endings as doors to brighter beginnings.",
    "I am open to the opportunities life places before me.",
    "My growth is steady, patient, and beautiful.",
    "I let go of old patterns that no longer serve me.",
    "I trust the timing of my life's unfolding.",
    "I step into each new chapter with confidence.",
    "I welcome challenges as teachers on my journey.",
    "My soul blooms with every season of change.",
    "I give myself permission to evolve and transform.",
    "I celebrate how far I've come and where I'm going.",
    "Each sunrise reminds me of fresh chances ahead.",
    "I outgrow fear and rise into freedom.",
    "I trust the process of my personal growth.",
    "I am ready for the new blessings entering my life.",
    "Change feels like an invitation to create anew.",
    "I choose progress over perfection in my journey.",
    "My spirit thrives on growth and new horizons.",
    "I am excited for the adventures that lie ahead.",
    "Today, I begin again with hope, strength, and love."
]
